"""Prompt-level frozen-F behavior labels for causal-z Stage1.

The manifest is deliberately independent from the retired trajectory cache:
it contains no hidden targets, NLLs, record ids, or rollout ids.  Its primary
key is a SHA-256 digest of the *rendered hidden-prompt token ids*.  The digest
is lineage/split metadata only and is never embedded or passed to R/F/D.

Direct correctness is always measured by deterministic greedy inference.
Native correctness is either generated by that backend or, for formal Stage1
training data, the exact existential label from validated Stage0 paired views.
"""

from __future__ import annotations

import hashlib
import json
import math
from pathlib import Path
from typing import Any, Callable, Mapping, Sequence


BEHAVIOR_MANIFEST_SCHEMA = 1
_LEGACY_BEHAVIOR_MANIFEST_SCHEMA = "thinkbridge-behavior-manifest-v7"
NATIVE_LABEL_SOURCES = frozenset({"generate", "stage0"})
_SHA256_HEX_LENGTH = 64
_NATIVE_PAIR_SPLITTER_V1 = "thinkbridge.exact-native-token-pair-v1"
_NATIVE_PAIR_SPLITTER_V2 = "thinkbridge.qwen-close-token-pair-v2"
_NATIVE_PAIR_SPLITTERS = frozenset({
    _NATIVE_PAIR_SPLITTER_V1,
    _NATIVE_PAIR_SPLITTER_V2,
})
_PROMPT_FIELDS = (
    "prompt_group_key",
    "direct_prompt_key",
    "prompt_token_count",
    "direct_prompt_token_count",
    "gold_answer_key",
    "has_correct_view",
    "n_correct",
    "direct_correct",
    "native_correct",
    "need_z",
    "native_think_complete",
    "native_cot_token_count",
    # Generated-validation manifests retain the exact token split from the
    # same frozen-F run that produced ``native_correct``.  Stage0-backed train
    # manifests use nulls because their canonical paired trajectory remains in
    # the validated Stage0 raw file.
    "native_cot_ids",
    "native_self_answer_ids",
    "native_hit_eos",
)


def _fingerprint_json(value: Any) -> str:
    encoded = json.dumps(
        value,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
        default=str,
    ).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def _is_sha256(value: Any) -> bool:
    return (
        isinstance(value, str)
        and len(value) == _SHA256_HEX_LENGTH
        and all(character in "0123456789abcdef" for character in value)
    )


def prompt_token_ids_key(token_ids: Sequence[int]) -> str:
    """Hash exact rendered prompt token ids for grouping and split isolation."""

    normalized: list[int] = []
    for token in token_ids:
        if isinstance(token, bool) or not isinstance(token, int) or token < 0:
            raise ValueError("rendered prompt token IDs must be nonnegative integers")
        normalized.append(int(token))
    if not normalized:
        raise ValueError("rendered prompt token IDs must not be empty")
    return _fingerprint_json(normalized)


def gold_answer_key(answer: str, task_type: str) -> str:
    """Return a lineage-only digest used to reject conflicting prompt labels."""

    normalized_answer = str(answer).strip()
    if not normalized_answer:
        raise ValueError("behavior manifest gold answer must not be empty")
    return _fingerprint_json({
        "answer": normalized_answer,
        "task_type": str(task_type).strip().lower(),
    })


def fingerprint_behavior_source(
    records: Sequence[Mapping[str, Any]],
    *,
    show_progress: bool = False,
    progress_desc: str = "Stage0: fingerprint source",
) -> str:
    """Fingerprint the ordered raw Stage0 source without mutating its records."""

    hasher = hashlib.sha256()
    record_iter: Any = records
    if show_progress:
        try:
            from tqdm.auto import tqdm
        except ImportError:
            pass
        else:
            record_iter = tqdm(
                records,
                total=len(records),
                desc=progress_desc,
                unit="record",
                dynamic_ncols=True,
            )
    for record in record_iter:
        encoded = json.dumps(
            record,
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
            default=str,
        ).encode("utf-8")
        hasher.update(len(encoded).to_bytes(8, "big"))
        hasher.update(encoded)
    hasher.update(len(records).to_bytes(8, "big"))
    return hasher.hexdigest()


def _behavior_prompt_fingerprint_payload(
    config: Any,
    tokenizer: Any,
) -> dict[str, Any]:
    """Return path-independent prompt-rendering semantics.

    Rendering-relevant tokenizer metadata is bound here. A filesystem location
    or executor digest is not part of the persisted behavior-data contract.
    """

    from think_bridge.data.templates import (
        THINK_BOUNDARY_TEXT,
        THINK_OPEN_TEXT,
        instruction_for_task,
    )

    task_type = str(config.task_type)
    return {
        "task_type": task_type,
        "think_instruction": instruction_for_task(task_type, think=True),
        "direct_instruction": instruction_for_task(task_type, think=False),
        "think_open_text": THINK_OPEN_TEXT,
        "think_boundary_text": THINK_BOUNDARY_TEXT,
        "tokenizer_class": type(tokenizer).__name__,
        "chat_template": getattr(tokenizer, "chat_template", None),
        "eos_token_id": getattr(tokenizer, "eos_token_id", None),
    }


def behavior_prompt_fingerprint(config: Any, tokenizer: Any) -> str:
    """Fingerprint the exact path-independent prompt rendering contract."""

    return _fingerprint_json(
        _behavior_prompt_fingerprint_payload(config, tokenizer)
    )


def legacy_behavior_prompt_fingerprint(
    config: Any,
    tokenizer: Any,
    *,
    tokenizer_name_or_path: str,
) -> str:
    """Reproduce the pre-relocation V7 prompt fingerprint exactly.

    This is validation-only compatibility for existing artifacts.  The caller
    must supply the ``tokenizer_source`` recorded inside that artifact; an
    arbitrary current path is never accepted as a legacy alias.
    """

    source = str(tokenizer_name_or_path).strip()
    if not source:
        raise ValueError("legacy tokenizer_name_or_path must not be empty")
    payload = _behavior_prompt_fingerprint_payload(config, tokenizer)
    payload["tokenizer_name_or_path"] = source
    return _fingerprint_json(payload)


def _validate_decode_contract(value: Any) -> None:
    if not isinstance(value, Mapping):
        raise ValueError("behavior manifest decode_contract must be an object")
    do_sample = value.get("do_sample")
    temperature = value.get("temperature")
    top_p = value.get("top_p")
    if do_sample is not False or isinstance(temperature, bool) or not isinstance(
        temperature, (int, float)
    ) or not math.isfinite(float(temperature)) or float(temperature) != 0.0:
        raise ValueError("behavior manifest requires deterministic greedy decoding")
    if (
        isinstance(top_p, bool)
        or not isinstance(top_p, (int, float))
        or not math.isfinite(float(top_p))
        or float(top_p) != 1.0
    ):
        raise ValueError("behavior manifest deterministic decoding requires top_p=1")
    for name in ("direct_max_new_tokens", "native_max_new_tokens"):
        count = value.get(name)
        if isinstance(count, bool) or not isinstance(count, int) or count <= 0:
            raise ValueError(f"behavior manifest {name} must be a positive integer")
    expected_implementations = {
        # Backend/version are separate mandatory provenance.  This field fixes
        # the shared greedy/EOS semantics used by either implementation.
        "decoder": "thinkbridge.greedy-token-decode-v1",
        "judge": "think_bridge.eval.answer_match.judge_answer",
    }
    for name, expected in expected_implementations.items():
        if value.get(name) != expected:
            raise ValueError(
                f"behavior manifest deterministic {name} contract is incompatible"
            )
    if value.get("native_pair_splitter") not in _NATIVE_PAIR_SPLITTERS:
        raise ValueError(
            "behavior manifest native_pair_splitter contract is incompatible"
        )


def deterministic_decode_contract(
    *,
    direct_max_new_tokens: int,
    native_max_new_tokens: int,
    native_label_source: str = "stage0",
) -> dict[str, int | float | bool | str]:
    """Build the backend-independent direct/native greedy semantics."""

    source = _validated_native_label_source(native_label_source)
    # Stage0 manifests contain no newly generated native token stream, so
    # their historical v1 splitter remains reusable.  Generated held-out
    # manifests use v2 and preserve the actual Qwen boundary token IDs.
    native_pair_splitter = (
        _NATIVE_PAIR_SPLITTER_V2
        if source == "generate"
        else _NATIVE_PAIR_SPLITTER_V1
    )

    value: dict[str, int | float | bool | str] = {
        "do_sample": False,
        "temperature": 0.0,
        "top_p": 1.0,
        "direct_max_new_tokens": direct_max_new_tokens,
        "native_max_new_tokens": native_max_new_tokens,
        "decoder": "thinkbridge.greedy-token-decode-v1",
        "judge": "think_bridge.eval.answer_match.judge_answer",
        "native_pair_splitter": native_pair_splitter,
    }
    _validate_decode_contract(value)
    return value


def _validated_inference_backend(value: Any) -> dict[str, str]:
    if not isinstance(value, Mapping):
        raise ValueError("behavior manifest inference_backend must be an object")
    name = value.get("name")
    version = value.get("version")
    if name not in {"hf", "vllm"}:
        raise ValueError("behavior manifest backend name must be 'hf' or 'vllm'")
    if not isinstance(version, str) or not version.strip():
        raise ValueError("behavior manifest backend version must not be empty")
    if set(value) != {"name", "version"}:
        raise ValueError("behavior manifest backend fields are incompatible")
    return {"name": str(name), "version": version.strip()}


def _validated_native_label_source(value: Any) -> str:
    if not isinstance(value, str) or value not in NATIVE_LABEL_SOURCES:
        raise ValueError(
            "behavior manifest native_label_source must be 'generate' or 'stage0'"
        )
    return value


def _validated_generation_layout(value: Any) -> dict[str, int | str]:
    if not isinstance(value, Mapping):
        raise ValueError("behavior manifest generation_layout must be an object")
    if set(value) != {"world_size", "batch_size", "rank_partition"}:
        raise ValueError("behavior manifest generation_layout fields are incompatible")
    world_size = value.get("world_size")
    batch_size = value.get("batch_size")
    partition = value.get("rank_partition")
    for name, count in (("world_size", world_size), ("batch_size", batch_size)):
        if isinstance(count, bool) or not isinstance(count, int) or count <= 0:
            raise ValueError(
                f"behavior manifest generation_layout.{name} must be positive"
            )
    if partition not in {"contiguous-v1", "interleaved-v1"}:
        raise ValueError(
            "behavior manifest generation_layout.rank_partition is incompatible"
        )
    return {
        "world_size": int(world_size),
        "batch_size": int(batch_size),
        "rank_partition": str(partition),
    }


def load_behavior_manifest(
    path: str | Path,
    *,
    prompt_fingerprint: str,
    decode_contract: Mapping[str, Any],
    source_fingerprint: str | None = None,
    inference_backend: Mapping[str, Any] | None = None,
    native_label_source: str | None = None,
    generation_layout: Mapping[str, Any] | None = None,
    legacy_prompt_fingerprint_for_tokenizer_source: (
        Callable[[str], str] | None
    ) = None,
    return_metadata: bool = False,
) -> (
    dict[str, dict[str, Any]]
    | tuple[dict[str, dict[str, Any]], dict[str, Any]]
):
    """Load and fail-closed validate a complete prompt-level behavior manifest."""

    manifest_path = Path(path)
    try:
        payload = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise RuntimeError(f"behavior manifest cannot be read: {manifest_path}") from exc
    if not isinstance(payload, dict):
        raise ValueError("behavior manifest must be a JSON object")
    if payload.get("schema_version") not in {
        BEHAVIOR_MANIFEST_SCHEMA,
        _LEGACY_BEHAVIOR_MANIFEST_SCHEMA,
    }:
        raise ValueError("behavior manifest schema version is incompatible")
    if payload.get("status") != "complete":
        raise ValueError("behavior manifest status must be 'complete'")
    metadata = payload.get("metadata")
    rows = payload.get("prompts")
    if not isinstance(metadata, dict) or not isinstance(rows, list):
        raise ValueError("behavior manifest requires metadata and a prompts array")
    stored_backend = _validated_inference_backend(
        metadata.get("inference_backend")
    )
    stored_native_label_source = _validated_native_label_source(
        metadata.get("native_label_source")
    )
    if native_label_source is not None:
        expected_native_label_source = _validated_native_label_source(
            native_label_source
        )
        if stored_native_label_source != expected_native_label_source:
            raise ValueError(
                "behavior manifest native_label_source differs from this request"
            )
    if stored_native_label_source == "stage0" and stored_backend["name"] != "hf":
        raise ValueError(
            "Stage 0 native labels require the HF direct backend"
        )
    if inference_backend is not None:
        expected_backend = _validated_inference_backend(inference_backend)
        if stored_backend != expected_backend:
            raise ValueError(
                "behavior manifest backend differs from the requested backend"
            )
    stored_generation_layout = metadata.get("generation_layout")
    if stored_generation_layout is not None:
        stored_generation_layout = _validated_generation_layout(
            stored_generation_layout
        )
    if generation_layout is not None:
        expected_generation_layout = _validated_generation_layout(
            generation_layout
        )
        if stored_generation_layout != expected_generation_layout:
            raise ValueError(
                "behavior manifest generation layout differs from this request"
            )
    supplied_fingerprints = {"prompt_fingerprint": prompt_fingerprint}
    if source_fingerprint is not None:
        supplied_fingerprints["source_fingerprint"] = source_fingerprint
    for name, value in supplied_fingerprints.items():
        if not _is_sha256(value):
            raise ValueError(f"expected {name} must be a SHA-256 digest")
    for name in ("prompt_fingerprint", "source_fingerprint"):
        if not _is_sha256(metadata.get(name)):
            raise ValueError(f"behavior manifest metadata {name} must be SHA-256")
    expected: dict[str, str] = {}
    if source_fingerprint is not None:
        expected["source_fingerprint"] = source_fingerprint
    for name, value in expected.items():
        if metadata.get(name) != value:
            raise ValueError(f"behavior manifest {name} differs from this run")
    stored_prompt_fingerprint = metadata.get("prompt_fingerprint")
    if stored_prompt_fingerprint != prompt_fingerprint:
        legacy_fingerprint = None
        if legacy_prompt_fingerprint_for_tokenizer_source is not None:
            tokenizer_source = metadata.get("tokenizer_source")
            if isinstance(tokenizer_source, str) and tokenizer_source.strip():
                legacy_fingerprint = (
                    legacy_prompt_fingerprint_for_tokenizer_source(
                        tokenizer_source
                    )
                )
                if not _is_sha256(legacy_fingerprint):
                    raise ValueError(
                        "behavior manifest legacy prompt fingerprint "
                        "resolver did not return a SHA-256 digest"
                    )
        if stored_prompt_fingerprint != legacy_fingerprint:
            raise ValueError(
                "behavior manifest prompt fingerprint differs from this run"
            )
    count = metadata.get("prompt_count")
    if (
        isinstance(count, bool)
        or not isinstance(count, int)
        or count <= 0
        or count != len(rows)
    ):
        raise ValueError("behavior manifest prompt_count differs from prompts")
    stored_decode_contract = metadata.get("decode_contract")
    _validate_decode_contract(stored_decode_contract)
    _validate_decode_contract(decode_contract)
    if dict(stored_decode_contract) != dict(decode_contract):
        raise ValueError("behavior manifest decode contract differs from evaluation")

    lookup = validate_behavior_rows(rows, native_label_source=stored_native_label_source,
                                    decode_contract=stored_decode_contract)
    if return_metadata:
        return lookup, dict(metadata)
    return lookup


def validate_behavior_rows(rows, *, native_label_source, decode_contract=None):
    """Validate actual labels and token targets, independently of producer metadata."""
    if not isinstance(rows, list) or not rows:
        raise ValueError("behavior prompts must be a nonempty array")
    stored_native_label_source = _validated_native_label_source(native_label_source)
    stored_decode_contract = decode_contract or {}
    lookup: dict[str, dict[str, Any]] = {}
    direct_labels: dict[str, tuple[bool, str]] = {}
    for index, row in enumerate(rows):
        if not isinstance(row, dict):
            raise ValueError(f"behavior manifest prompts[{index}] must be an object")
        missing = [name for name in _PROMPT_FIELDS if name not in row]
        if missing:
            raise ValueError(
                f"behavior manifest prompt is missing {missing}: index={index}"
            )
        prompt_key = row["prompt_group_key"]
        direct_key = row["direct_prompt_key"]
        answer_key = row["gold_answer_key"]
        if not _is_sha256(prompt_key):
            raise ValueError(f"invalid prompt_group_key at index={index}")
        if not _is_sha256(direct_key):
            raise ValueError(f"invalid direct_prompt_key: {prompt_key}")
        if not _is_sha256(answer_key):
            raise ValueError(f"invalid gold_answer_key: {prompt_key}")
        if prompt_key in lookup:
            raise ValueError(f"behavior manifest duplicate prompt_group_key: {prompt_key}")
        for name in ("prompt_token_count", "direct_prompt_token_count"):
            value = row[name]
            if isinstance(value, bool) or not isinstance(value, int) or value <= 0:
                raise ValueError(f"invalid behavior manifest {name}: {prompt_key}")
        n_correct = row["n_correct"]
        if isinstance(n_correct, bool) or not isinstance(n_correct, int) or n_correct < 0:
            raise ValueError(f"invalid behavior manifest n_correct: {prompt_key}")
        booleans = (
            row["has_correct_view"],
            row["direct_correct"],
            row["native_correct"],
            row["need_z"],
        )
        if any(not isinstance(value, bool) for value in booleans):
            raise ValueError(f"behavior labels must be Boolean: {prompt_key}")
        if row["has_correct_view"] is not (n_correct > 0):
            raise ValueError(
                f"has_correct_view and n_correct differ: {prompt_key}"
            )
        expected_need_z = row["native_correct"] and not row["direct_correct"]
        if row["need_z"] is not expected_need_z:
            raise ValueError(f"need_z differs from direct/native labels: {prompt_key}")
        native_cot_count = row["native_cot_token_count"]
        native_complete = row["native_think_complete"]
        native_cot_ids = row["native_cot_ids"]
        native_answer_ids = row["native_self_answer_ids"]
        native_hit_eos = row["native_hit_eos"]
        native_boundary_ids = row.get("native_boundary_ids")
        if stored_native_label_source == "stage0":
            if row["native_correct"] is not row["has_correct_view"]:
                raise ValueError(
                    "Stage 0 native_correct must equal "
                    f"has_correct_view: {prompt_key}"
                )
            # Stage0 supplies an existential prompt-level correctness label,
            # not one new deterministic native trajectory.  Nulls prevent an
            # arbitrary sampled CoT from masquerading as that nonexistent run.
            if (
                native_complete is not None
                or native_cot_count is not None
                or native_cot_ids is not None
                or native_answer_ids is not None
                or native_hit_eos is not None
                or native_boundary_ids is not None
            ):
                raise ValueError(
                    "Stage 0 native labels must not fabricate "
                    f"native trajectory metadata: {prompt_key}"
                )
        else:
            if not isinstance(native_complete, bool):
                raise ValueError(
                    "behavior manifest generated native_think_complete "
                    f"must be Boolean: {prompt_key}"
                )
            if not isinstance(native_hit_eos, bool):
                raise ValueError(
                    "generated native_hit_eos must be Boolean: "
                    f"{prompt_key}"
                )
            splitter = stored_decode_contract.get("native_pair_splitter")
            if splitter == _NATIVE_PAIR_SPLITTER_V2 and (
                "native_boundary_ids" not in row
            ):
                raise ValueError(
                    "generated native pair lacks native_boundary_ids: "
                    f"{prompt_key}"
                )
            if native_complete:
                if (
                    isinstance(native_cot_count, bool)
                    or not isinstance(native_cot_count, int)
                    or native_cot_count < 0
                ):
                    raise ValueError(
                        "native_think_complete=true requires a nonnegative "
                        f"native_cot_token_count: {prompt_key}"
                    )
                token_fields = [
                    ("native_cot_ids", native_cot_ids),
                    ("native_self_answer_ids", native_answer_ids),
                ]
                if splitter == _NATIVE_PAIR_SPLITTER_V2:
                    token_fields.append(
                        ("native_boundary_ids", native_boundary_ids)
                    )
                for field_name, token_values in token_fields:
                    if not isinstance(token_values, list) or any(
                        isinstance(token, bool)
                        or not isinstance(token, int)
                        or token < 0
                        for token in token_values
                    ):
                        raise ValueError(
                            f"behavior manifest {field_name} must be a nonnegative token array: "
                            f"{prompt_key}"
                        )
                if len(native_cot_ids) != native_cot_count:
                    raise ValueError(
                        "native_cot_ids and count differ: "
                        f"{prompt_key}"
                    )
                if not native_cot_ids or not native_answer_ids:
                    raise ValueError(
                        "a complete native pair requires non-empty CoT and answer: "
                        f"{prompt_key}"
                    )
                if (
                    splitter == _NATIVE_PAIR_SPLITTER_V2
                    and not native_boundary_ids
                ):
                    raise ValueError(
                        "a generated native boundary must not be empty: "
                        f"{prompt_key}"
                    )
                if not native_hit_eos:
                    raise ValueError(
                        "a complete native pair must terminate with EOS: "
                        f"{prompt_key}"
                    )
            elif (
                native_cot_count is not None
                or native_cot_ids is not None
                or native_answer_ids is not None
                or native_boundary_ids is not None
            ):
                raise ValueError(
                    "native_think_complete=false requires "
                    f"native trajectory fields=null: {prompt_key}"
                )
        direct_signature = (bool(row["direct_correct"]), str(answer_key))
        previous_direct = direct_labels.get(str(direct_key))
        if previous_direct is not None and previous_direct != direct_signature:
            raise ValueError(
                "labels or gold conflict for one rendered direct prompt: "
                f"{direct_key}"
            )
        direct_labels[str(direct_key)] = direct_signature
        normalized_row = {name: row[name] for name in _PROMPT_FIELDS}
        # Additive v2 provenance.  Historical Stage0/v1 rows intentionally
        # omit this field and normalize to None without invalidating lineage.
        normalized_row["native_boundary_ids"] = native_boundary_ids
        observation_fields = ("native_generated_ids", "native_observed_cot_ids",
                              "native_observed_cot_token_count")
        if any(name in row for name in observation_fields):
            if not all(name in row for name in observation_fields):
                raise ValueError("native observed-token provenance is incomplete")
            generated, observed, count = (row[name] for name in observation_fields)
            if stored_native_label_source == "stage0":
                if any(value is not None for value in (generated, observed, count)):
                    raise ValueError("sample-backed behavior cannot invent a greedy observed trajectory")
            else:
                if any(not isinstance(tokens, list) or any(isinstance(t, bool) or not isinstance(t, int) or t < 0
                       for t in tokens) for tokens in (generated, observed)):
                    raise ValueError("native observed provenance requires actual nonnegative token arrays")
                if isinstance(count, bool) or not isinstance(count, int) or count != len(observed):
                    raise ValueError("native observed CoT count differs from exact tokens")
                if generated[:count] != observed or (native_cot_ids is not None and observed != native_cot_ids):
                    raise ValueError("native observed CoT differs from generated prefix or paired target")
            normalized_row.update({name: row[name] for name in observation_fields})
        lookup[str(prompt_key)] = normalized_row
    return lookup


__all__ = [
    "BEHAVIOR_MANIFEST_SCHEMA",
    "NATIVE_LABEL_SOURCES",
    "behavior_prompt_fingerprint",
    "legacy_behavior_prompt_fingerprint",
    "deterministic_decode_contract",
    "fingerprint_behavior_source",
    "gold_answer_key",
    "load_behavior_manifest",
    "prompt_token_ids_key",
]
